export default {
    path:'/movie',
    component:()=>import('@/views/Movie'),
    // 配置movie页面的二级路由
    children:[
        {
            path:'city',
            component:()=>import('@/components/City')
        },{
            path:'nowhot',
            component:()=>import('@/components/NowHot')
        },{
            path:'comingsoon',
            component:()=>import('@/components/ComingSoon')
        },{
            path:'search',
            component:()=>import('@/components/Search')
        },{
            path:'detail/1/:movieId',
            components:{
                default:()=>import('@/components/NowHot'),
                detail:()=>import('@/views/Movie/detail')
            },
            props:{
                detail:true
            }
        },{
            path:'detail/2/:movieId',
            components:{
                default:()=>import('@/components/ComingSoon'),
                detail:()=>import('@/views/Movie/detail')
            },
            props:{
                detail:true
            }
        },{
            path:"/movie",
            redirect:'/movie/nowhot'
        }
    ]
}